# Generated by Django 5.1.3 on 2024-11-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_comments_images/'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_comments_videos/'),
        ),
    ]
